sudo: required

matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      cache:
      yarn: true
      directories:
        - node_modules
      branches:
        only:
          - master
      before_script:
        - cd node
        - yarn install
      os:
        - linux
      script: yarn run wp:prod

    - language: csharp
      mono: none
      dotnet: 2.0.0
      dist: trusty
      branches:
        only:
          - master
      before_script:
        - cd app.web
        - dotnet restore
        - cd ..
        - cd app.test
      os:
        - linux
      script:
        - dotnet restore && dotnet xunit