sudo: required

language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
  - master

before_script:
  - cd node
  - yarn install

os:
  - linux

script: yarn run wp:prod